### PR TITLE
🚧 🤖📯 Webhooks changed

### PR DESCRIPTION
**Pull request by G-Rath**
A new release of [@octokit/webhooks](https://github.com/octokit/webhooks) was just released!
This PR updates that package, along with copying the schemas & regenerating the types that are derived from `@octokit/webhooks`.

### CODE REVIEW

**Comment by G-Rath** [comment]
@gr2m except now the PR comes from me, meaning I don't get notifications about it being opened :(

(context: I've switched from using `github.GITHUB_TOKEN` to a personal access token)

**Comment by gr2m** [comment]
The CI is still not triggered, even if you set `github.GITHUB_TOKEN` to a personal access token, because of `actions/checkout@v2`

https://github.com/G-Rath/compare-gh-webhook-to-schema-function/blob/dc8ec15b045beddae7b9e7ef18824b086f2fe1a3/.github/workflows/update.yml#L18

It should work with v1. I want to see if I can workaround it.

Regarding the notification: use a bot account :D

**Comment by G-Rath** [comment]
> The CI is still not triggered,

Yeah I noticed that it hadn't for the second commit, but it seems to have triggered for the first commit? 

image

> Regarding the notification: use a bot account :D

I thought Github only liked you having a single account per email 😜

-------

For the meantime I'll probably just restore back to using the github token and enable manually triggering the workflow 🤷

**Comment by gr2m** [comment]
as an alternative, you could use your account to create / update the PR, but use `secrets.GITHUB_TOKEN` to add a comment in order to be notified. For small single request hacks like this you can use https://github.com/octokit/request-action/

**Comment by G-Rath** [comment]
Couldn't I use that action to trigger running the `checks` workflow against this branch (after adding `workflow_dispatch` to the action) as part of the `update` workflow? 🤔

**Comment by gr2m** [comment]
sorry I don't quite get what you mean? Excuse my brain today, I'm very tired

**Comment by G-Rath** [comment]
You can trigger workflows with [workflow dispatch events](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) right?

So I should be able to have the `update` workflow trigger the `checks` workflow to run against the PR (and/or its branch) via the REST API.

I could do that with plain cURL, but then the action you linked to would make it even easier to do :)

**Comment by gr2m** [comment]
> You can trigger workflows with [workflow dispatch events](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) right?

Yes



> So I should be able to have the `update` workflow trigger the `checks` workflow to run against the PR (and/or its branch) via the REST API.

Got it. Yes, that should work 👍🏼

**Pull request merged**
